### ISSUE TITLE
Unable to connect to meeting with message: "Sorry, we couldn't connect you."

### ISSUE THREAD

**Issue by banderlog** [dev-rke/teams-phone-fix#1]
subj, on Google Chrome all is fine

Firefox 71.0 amd64 on Ubuntu 18.04 LTS

**UPD:**  using [User-Agent Switcher](https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/) I was able to join meeting using "Windows/Chrome 79" identity: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Comment by dev-rke** [comment]
Hi @banderlog ,

Happy new Year!
Thanks for your pull request.
I already found that out over two months ago, unfortunately i had no time to finish my refactoring.
You are now able to define whatever user agent you like. 
You may also use this to communicate messages to the Microsoft Teams Developers to support all modern browsers by using some customized user agents. ;-)

Please find the brand new version 1.1.0 on https://addons.mozilla.org/en-US/firefox/addon/teams-phone-fix/. I also would appreciate a vote or comment.
