### ISSUE TITLE
I can't see anybody's video in the meeting

### ISSUE THREAD

**Issue by jaumebecks** [dev-rke/teams-phone-fix#15]
Hi! This extension works pretty fine overall for me, but I'm having an issue when joining a call: **I can't see anybody's video in the meeting!**, all I see are the squares of everybody else with their initials. It happens also when changing the preview to Gallery, and all other options.
 
I don't know why, and if it's related to be using this extension wrong, do you have any idea about how to solve this? 

I'm using Firefox 105.0 (64-bit) on Ubuntu 22.04

Many thanks

**Comment by dev-rke** [comment]
Hi @jaumebecks,

Thanks for using the extension and your feedback. :-)
This extension does not modify the behaviour of Microsoft Teams, so it won't solve bugs of Teams. 
The concept of the extension is to circumvent the warning message when accessing the Teams web application by simulating a different user agent, e.g. of Google Chrome or Microsoft Edge. This might cause bugs, as Microsoft did not optimize nor test Firefox with the Teams web application.
If you like to have video support of Teams in Firefox, please send a feature request to Microsoft to implement this feature.

In the meantime, i'd recommend to use Chrome or Edge to have a better feature support. 
Another alternative is the native Teams application, which is already available for all operating systems (including Linux).
