### ISSUE TITLE
Recipient Complains of Echoing

### ISSUE THREAD

**Issue by unL33T123** [dev-rke/teams-phone-fix#18]
When I call from Firefox while using this plug in the person I am calling complains they can hear themselves.

If I call using Brave (which doesn't require this extension), with exactly the same settings, there is no echo heard.

I am running Firefox 117.0.1 64 bit on Windows 10.  I am using a headset.

Thanks!

**Comment by dev-rke** [comment]
Hi @unL33T123 ,

Brave is as far as i know based on Chromium, which has been founded by Google and is also used by Google Chrome and Microsoft Edge. So it is clear, that Brave should work without any big flaws.
This extension does not change the behaviour of Microsoft Teams, it just circumvents some restrictions Microsoft provided by simulating the user agent of Chrome / Edge. This can from time to time enable better features, but can also lead to unexpected behaviour, depending on what Microsoft implements over time.
Therefore this ticket will be closed.

I recommend to complain to Microsoft for better Teams support in Firefox, this would help all of us. :-)
