### ISSUE TITLE
there are more than one domain associated with the app

### ISSUE THREAD

**Issue by avoidik** [dev-rke/teams-phone-fix#6]
hi,

thank you for this nice addon (on chrome I'm using similar addon named [modheader](https://bewisse.com/modheader)), just wanted to let you know that there are more than one domain being used by MSTeams application, do we need to handle all of them? like https://github.com/dev-rke/teams-phone-fix/pull/5

**Comment by dev-rke** [comment]
Hi @avoidik ,

is there any reason why this might be necessary?
In my opinion the browser condition of Teams is in the beginning, when the application is loaded from teams.microsoft.com.

Does the behaviour change when applying your patch? 
E.g. working video calls or something like that?
If it is not necessary, i would like to not apply that patch, as it requires more domains to be accessed.

**Comment by grahamperrin** [comment]
Also `teams.live.com` for _Teams for friends and family_ …
